name: Build TPMImport

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: dotnet restore -r win-x64 TPMImport.csproj

    - name: Publish
      run: dotnet publish -p:Version=1.3.$GITHUB_RUN_NUMBER.500 --configuration Release --no-restore -r win-x64 -p:PublishSingleFile=true --self-contained false TPMImport.csproj
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: tpmimport-win-x64
        path: bin/Release/net6.0-windows/win-x64/publish/*